### ISSUE TITLE
Unintuitive Configuration

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-WastelessWatering#1]
With the addition of the hold to use function, the ToggleKey entry in the config file should probably be named to something more intuitive to both applications. I kept thinking the toggle key would turn the mod on and off, and it's actually now the bypass.
The mod also comes default with hold mode on, but with the hotkey bount to alt plus comma, which might be a bit awkward to use. It might be better to make the default binding just the alt keys.

**Comment by GrumpyCrouton** [comment]
If you want to give me a better name for the field then I'm down to consider it. I couldn't think of anything better myself. `Toggle` just means to turn it on or off, which it still does even in hold mode. It just toggles it temporarily. 

Also, Hold Mode is supposed to be off by default, so I will probably be changing that. I may have turned it on when I was testing it.

Also also, the default key should be left or right Shift + ,

**Comment by GrumpyCrouton** [comment]
@Bartholomue I still haven't been able to think of a better name. I'll close this issue if we can't come up with one

**Comment by Bartholomue** [comment]
AlternativeBehavior? Since the key is having the mod perform an alternative action to what's defined by the on/off configuration option.

**Comment by GrumpyCrouton** [comment]
@Bartholomue that seems less descriptive than toggle to me
